### ISSUE TITLE
Combat casting doesn't use correct cantrip level

### ISSUE THREAD

**Issue by dolenam317** [Holic75/SolastaExtraContent#4]
When combat casting feat is selected and character cast a cantrip when perform AOO the level of the cantrip is not scaled with character level. Tested with sacred flame and sun blade with caster level above 5.
- Sacred flame is always 1d8,
- Sun blade trigger the highlight but doesn't add 1d8 extra radiant damage.

**Comment by Holic75** [comment]
Unable to reproduce the issue based on information you provided.  Tried on Arcane knight and all cantrips scaled correctly for me. Try getting latest version of ModHelpers, ExtraContent, uninstall all other mods except ModApi; if the issue persists, send me the save and exact steps to reproduce the issue.
