### ISSUE TITLE
Make level 6...9 spells available to Warlock's Magic Arcanum

### ISSUE THREAD

**Issue by DONStefan** [Holic75/SolastaExtraContent#5]
Hello Holic,

I'm playing Solasta with EC and CE. The bard can be played beyond level 12 by selecting CE spells level 6...9 for them.

For the Warlock, it's not possible to do that. They will be displayed under "unlearn spell", but not under "class spells".

Would it be possible to fix this?

**Comment by Holic75** [comment]
This should be done from CE by adding corresponding spells to WarlockClassMysticArcanumSpellList{i}, since they are the ones who introduced these spells, and they have already took initiative to add their spells to other classes.
